<div id="container" class="boxWhite container">
    <div class="content">
        <h2>COMO ESCREVER A HISTÓRIA</h2>
        <h3>
            Sua trajetória pode abrir caminho<br />
            para milhares de outras mulheres
        </h3>
        <p>O relato poder&aacute; ser feito por escrito, via formul&aacute;rio a ser retirado no SEBRAE ou pelo site.</p>
        <p>No site, o sistema controla o tamanho do relato, que deve ter, no m&iacute;nimo, 500 (quinhentas) e no m&aacute;ximo 1.200 (mizl e duzentas) palavra, incluindo o t&iacute;tulo. Textos com tamanho menor ou maior ao limite acima n&atilde;o ser&atilde;o considerados. Os relatos escritos &agrave; m&atilde;o dever&atilde;o ter, no m&iacute;nimo, 60 (sessenta) linhas, e n&atilde;o poder&atilde;o ultrapassar o limite de 120 (cento e vinte) linhas. caso contrario n&atilde;o ser&atilde;o considerados.</p>
        <p>Ao escrever o seu relato, lembra-se que a narrativa precisa &ldquo;prender&rdquo; a aten&ccedil;&atilde;o do leitor. Por isso, deve transmitir emo&ccedil;&atilde;o. A historia deve ser real e verdadeira, pois na fase de visitas as informa&ccedil;&otilde;es ser&atilde;o conferidas.</p>
        <p>&Eacute; desej&aacute;vel destacar valores positivos, que possam incentivar outras mulheres, tais como: iniciativa, vis&atilde;o de futuro, pensamento sist&ecirc;mico, aprendizado, inova&ccedil;&atilde;o, valoriza&ccedil;&atilde;o das pessoas e do g&ecirc;nero feminino, planejamento, estabelecimento de metas, busca de informa&ccedil;&otilde;es e de oportunidades. Caso algumas destas caracter&iacute;sticas estejam presentes no seu caminho de empreendedora, destaque-as em sua narrativa.</p>
        <p>Roteiro para escrever o seu relato</p>
        <p>Para contar o seu relato como Mulher de Neg&oacute;cio, voc&ecirc; poder&aacute; considerar os seguintes pontos:</p>
        <p>Titulo do relato (1 linha)</p>
        <p>O titulo &eacute; uma forma de resumir o que &eacute; mais importante.<br />Sugest&atilde;o: escreva por &uacute;ltimo o t&iacute;tulo depois do relato pronto.</p>
        <p>Cria&ccedil;&atilde;o do Neg&oacute;cio: Conte como tudo come&ccedil;ou<br />&bull; Quais as informa&ccedil;&otilde;es foram utilizadas para a cria&ccedil;&atilde;o do sonho?<br />&bull; O que ou quem a inspirou a montar o seu neg&oacute;cio?<br />&bull; Quais novidades ou tend&ecirc;ncias buscava trazer ao iniciar o seu neg&oacute;cio?<br />&bull; O que seu produto ou servi&ccedil;o tinha de diferente dos outros? <br />&bull; Como o fato de ser mulher influenciou na sua decis&atilde;o de abrir o seu neg&oacute;cio?<br />&bull; Voc&ecirc; acha que teve dificuldades especificas por ser mulher? Se sim, quais a&ccedil;&otilde;es criativas buscou para enfrentar as dificuldades?</p>
        <p>Desenvolvimento (Condu&ccedil;&atilde;o) do Neg&oacute;cio: Conte como as coisas acontecem no seu dia- a - dia</p>
        <p>&bull; De que maneira aplica seus valores pessoais na administra&ccedil;&atilde;o do neg&oacute;cio? <br />&bull; Como compartilha as informa&ccedil;&otilde;es? Consulta ou envolve seus colaboradores nas tomadas de decis&atilde;o?<br />&bull; Como est&aacute; estruturado o seu neg&oacute;cio (regra de funcionamento, pessoas envolvidas, e local de suas atividades)?<br />&bull; D&ecirc; exemplos do bom uso dos recursos de que disp&otilde;e.<br />&bull; Como voc&ecirc; participa da condu&ccedil;&atilde;o das atividades do seu neg&oacute;cio, incluindo relacionamento com clientes, colaboradores, fornecedores, comunidades e parceiros?<br />&bull; Como voc&ecirc; reage diante dos desafios ou obst&aacute;culos na condu&ccedil;&atilde;o do seu neg&oacute;cio?<br />&bull; Como s&atilde;o selecionados seus colaboradores? H&aacute; uma preocupa&ccedil;&atilde;o com a redu&ccedil;&atilde;o da desigualdade social?<br />&bull; Quais benef&iacute;cios s&atilde;o oferecidos aos seus colaboradores para que sintam mais motivados?<br />&bull; O que voc&ecirc; faz para torna o ambiente de trabalho mais agrad&aacute;vel? Cite exemplos.</p>
        <p>Resultados: Realiza&ccedil;&otilde;es e Contribui&ccedil;&otilde;es:<br />&bull; Qual solu&ccedil;&atilde;o adotou como resultado do amadurecimento do neg&oacute;cio, problemas enfrentados, ou dos relacionamentos mantidos? Se voc&ecirc; pudesse voltar no tempo, faria algo diferente? Cite exemplos de melhoria realizadas que partiram de li&ccedil;&otilde;es aprendidas com os erros cometidos em seu neg&oacute;cio.<br />&bull; Como voc&ecirc; percebe que seu neg&oacute;cio esta melhorando (aumento do faturamento, de clientes, melhoria da qualidade dos produtos/servi&ccedil;os, satisfa&ccedil;&atilde;o dos colaboradores)?<br />&bull; O que pensa para o futuro do seu neg&oacute;cio?<br />&bull; Quais s&atilde;o os pr&oacute;ximos passos para assegurar o futuro do seu neg&oacute;cio ( planos e metas)?<br />&bull; Como o seu neg&oacute;cio serve de exemplo para a forma&ccedil;&atilde;o de novas empreendedoras?<br />&bull; Em sua opini&atilde;o, o que &eacute; preciso fazer para ter sucesso como empreendedora?<br />&bull; Que mensagem gostaria de passar para as mulheres que est&atilde;o iniciando o seu neg&oacute;cio?</p>
    </div>
</div>
